use_frameworks!

platform :ios, '8.0'

target 'LiMaoBase_Example' do
  pod 'LiMaoBase', :path => '../'

  target 'LiMaoBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
