use_frameworks!

platform :ios, '8.0'

target 'LiMaoLogin_Example' do
  pod 'LiMaoLogin', :path => '../'

  target 'LiMaoLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
